name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build et push de l’image Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mon-image:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mon-image:latest
