name: Github CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Client Docker image
        run: |
          set -e  # Fail the script if any command fails
          cd client/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/client:latest .

      - name: Save Client Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: client-image
          path: client/

  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Server Docker image
        run: |
          set -e  # Fail the script if any command fails
          cd server/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/server:latest .

      - name: Save Server Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: server-image
          path: server/

  deploy-client:
    runs-on: ubuntu-latest
    needs: [build-client]  # Wait for both build jobs

    steps:
      - name: Download Client Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: client-image
          path: client/

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Client Docker image
        run: |
          set -e  # Fail the script if any command fails
          docker push ${{ secrets.DOCKER_USERNAME }}/client:latest

  deploy-server:
    runs-on: ubuntu-latest
    needs: [build-server]  # Wait for both build jobs

    steps:
      - name: Download Server Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: server-image
          path: server/

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Server Docker image
        run: |
          set -e  # Fail the script if any command fails
          docker push ${{ secrets.DOCKER_USERNAME }}/server:latest
